/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ATU_Program;

import java.io.*;
import atu.input.*;
public class Library extends Exception{
	public static void main(String[] args) throws Exception {
		String csvFile = ".\\csv\\\\Sample Student Data File.csv";
		UIApplication.read(csvFile);
		System.out.println("ATU Program start!");
		UIApplication.launch(UIApplication.class, args);
	}
}

