///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package ATU_Program;
//
//import org.junit.Test;
//
//import atu.input.Person;
//
//import org.junit.Before;
//import static org.junit.Assert.*;
//
//public class LibraryTest {
//	int[] arrAscending, arrDescending;
//	Person testStu;
//	@Before
//	public void setUp() throws Exception {
//        testStu = new Person("20760735","HUANG Haolun","50","50","1","1","0","hellow","26");
//	}
//    @Test public void testSomeLibraryMethod() {
//        assertEquals("20760735", testStu.getStudentid());
//    }
//}
