/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ATU_Program;

import org.junit.Test;

import atu.input.PeopleList;
import atu.input.Person;
import atu.input.Statistics;
import atu.input.UIApplication;

import org.junit.Before;
import static org.junit.Assert.*;

import java.beans.Transient;

public class LibraryTest {
	private float[] k1_energy = { 0, 100, 0 };
	private float[] k2_energy = { 0, 100, 0 };
	String csvFile = ".\\csv\\\\Sample Student Data File.csv";
	Person testStu;
	Person testStu1;
	Statistics testStat;
	PeopleList testList;

	@Before
	public void setUp() throws Exception {
		testStu = new Person("20760735", "HUANG Haolun", "50", "50", "1", "1", "0", "hellow", "26");
		testStu1 = new Person("20760735", "HUANG Haolun", "50", "50", "1", "1", "", "hellow", "26");
		testStat = new Statistics("entry", "value", "0");
		testList = new PeopleList(k1_energy, k2_energy, 1, 1, 10);

	}

	@Test
	public void testgetid() {
		assertEquals("20760735", testStu.getStudentid());
	}

	@Test
	public void testSetid() {
		testStu.setStudentid("20114514");
		assertEquals("20114514", testStu.getStudentid());
	}

	@Test
	public void testgetname() {
		assertEquals("HUANG Haolun", testStu.getStudentname());
	}

	@Test
	public void testSetname() {
		testStu.setStudentname("Jay Chou");
		assertEquals("Jay Chou", testStu.getStudentname());
	}

	@Test
	public void testgetK1() {
		assertEquals(50, testStu.getK1energy());
	}

	@Test
	public void testSetK1() {
		testStu.setK1energy("10");
		assertEquals(10, testStu.getK1energy());
	}

	@Test
	public void testgetK2() {
		assertEquals(50, testStu.getK2energy());
	}

	@Test
	public void testSetK2() {
		testStu.setK2energy("10");
		assertEquals(10, testStu.getK2energy());
	}

	@Test
	public void testgetK3T1() {
		assertEquals(1, testStu.getK3trick1());
	}

	@Test
	public void testSetK3T1() {
		testStu.setK3trick1("2");
		assertEquals(2, testStu.getK3trick1());
	}

	@Test
	public void testgetK3T2() {
		assertEquals(1, testStu.getK3trick2());
	}

	@Test
	public void testSetK3T2() {
		testStu.setK3trick2("2");
		assertEquals(2, testStu.getK3trick2());
	}

	@Test
	public void testgetPref() {
		assertEquals(0, testStu.getMypreference());
	}
	
	@Test
	public void testgetPref2() {
		assertEquals(0, testStu1.getMypreference());
	}

	@Test
	public void testSetPref() {
		testStu.setMypreference("1");
		assertEquals(1, testStu.getMypreference());
	}

	@Test
	public void testgetConcerns() {
		assertEquals("hellow", testStu.getConcerns());
	}

	@Test
	public void testSetConcerns() {
		testStu.setConcerns("hi");
		assertEquals("hi", testStu.getConcerns());
	}

	@Test
	public void testgetEntry() {
		assertEquals("entry", testStat.getEntry());
	}

	@Test
	public void testSetEntry() {
		testStat.setEntry("new entry");
		assertEquals("new entry", testStat.getEntry());
	}

	@Test
	public void testgetValue() {
		assertEquals("value", testStat.getValue());
	}

	@Test
	public void testSetValue() {
		testStat.setValue("new value");
		assertEquals("new value", testStat.getValue());
	}

	@Test
	public void testgetIndex() {
		assertEquals("0", testStat.getIndex());
	}

	@Test
	public void testSetIndex() {
		testStat.setIndex("1");
		assertEquals("1", testStat.getIndex());
	}
	
	@Test
	public void testgetTeam() {
		assertEquals(0, testStu.get_team_id());
	}

	@Test
	public void testgetK1Energy() {
		assertArrayEquals(k1_energy, testList.getk1(), 0.01f);
	}

	@Test
	public void testSetK1Energy() {
		float[] new_k1_energy = { 0, 50, 0 };
		testList.setk1(new_k1_energy);
		assertArrayEquals(new_k1_energy, testList.getk1(), 0.01f);
	}

	@Test
	public void testgetK2Energy() {
		assertArrayEquals(k2_energy, testList.getk2(), 0.01f);
	}

	@Test
	public void testSetK2Energy() {
		float[] new_k2_energy = { 0, 50, 0 };
		testList.setk2(new_k2_energy);
		assertArrayEquals(new_k2_energy, testList.getk2(), 0.01f);
	}

	@Test
	public void testgetK3T1Energy() {
		assertEquals(1, testList.getk3t1());
	}

	@Test
	public void testSetK3T1Energy() {
		testList.setk3t1(2);
		assertEquals(2, testList.getk3t1());
	}

	@Test
	public void testgetK3T2Energy() {
		assertEquals(1, testList.getk3t2());
	}

	@Test
	public void testSetK3T2Energy() {
		testList.setk3t2(2);
		assertEquals(2, testList.getk3t2());
	}

	@Test
	public void testgetPrefEnergy() {
		assertEquals(10, testList.getpref());
	}

	@Test
	public void testSetPrefEnergy() {
		testList.setpref(20);
		assertEquals(20, testList.getpref());
	}

	@Test
	public void testaddStudent() {
		testList.addStudent(testStu);
		assertEquals(1, testList.size());
	}

	@Test
	public void testSize() {
		assertEquals(0, testList.size());
	}

//	@Test
//	public void testRead() {
//		UIApplication.read(csvFile);
//		assertEquals(12, UIApplication.read(csvFile).getk3t1());
//	}
}
